### ISSUE TITLE
Builds written to sdcard not booting

### ISSUE THREAD

**Issue by zinke22** [limepepper/ansible-role-raspberrypi#21]
Followed instruction to build restore image on 32g sdcard Raspbian lite 32 bit
All went ok
Write restore img to card, inserted int rPi. 
rPi unresponsive

**Comment by tolland** [comment]
what distro/OS are you building on?
is there anything on the screen when it goes unresponsive?

**Comment by zinke22** [comment]
Hi, built on rPi 3B+ and a lubuntu pc with both full and lite 2021-05-07.
Tried lwriting with DD and Imager.
Card in rPi, ethernet connected, power on, cannot ssh. Scanner shows no
network connection

**Comment by tolland** [comment]
If you mount the sdcard and paste your current `/boot/cmdline.txt` `/etc/fstab` and also the output of `blkid /dev/sdX*`, it might indicate where the problem is.

**Comment by zinke22** [comment]
Hi, Just did a rebuild with the latest code and it has worked! Well done! Thanks

**Comment by tolland** [comment]
Cool!
