### ISSUE TITLE
Make Promptless?

### ISSUE THREAD

**Issue by myxxmikeyxx** [limepepper/ansible-role-raspberrypi#28]
Can I run the script so I don't have to keep kitting enter like 5 times when I want to make a reset image?

**Comment by tolland** [comment]
don't use the `-s` option, it's only there for debugging (or if you are really interested in what its doing at each step)

**Comment by myxxmikeyxx** [comment]
That's just what I needed. I was using the command from the wiki that had -a -s and I was not sure what it did and did not want to mess it up. Thank you very much!
