### ISSUE TITLE
Alter create-factory-reset to handle newer release of raspbian-stretch-lite?

### ISSUE THREAD

**Issue by andrewpainton** [limepepper/ansible-role-raspberrypi#6]
I apologize for my lack of knowledge but Is it possible for the create-facotry to, rather than attempt to use a 2018 raspbian-stretch-lite image to grab the one that was created  from infating after downloading? 

current ex. "2020-02-13-raspbian_buster_lite"

**Comment by tolland** [comment]
I've not tested it for some time. However unless they have changed the layout it should work with newer images

**Comment by vildasha** [comment]
Hi, scrips not working with newer version of raspbian

pi@raspberrypi:/ansible-role-raspberrypi/files $ `sudo bash ./create-factory-reset`

entering main function
Not found source image '2018-10-09-raspbian-stretch-lite.img'
pi@raspberrypi:/ansible-role-raspberrypi/files $

**Comment by daanbreur** [comment]
```bash
daan@DESKTOP-OGEP42C:/mnt/d/hackingToolkit/raspberry-pi-factory-reset$  unzip raspbian_lite_latest
Archive:  raspbian_lite_latest
  inflating: 2020-02-13-raspbian-buster-lite.img
daan@DESKTOP-OGEP42C:/mnt/d/hackingToolkit/raspberry-pi-factory-reset$ losetup -a -v
daan@DESKTOP-OGEP42C:/mnt/d/hackingToolkit/raspberry-pi-factory-reset$ sudo bash ./create-factory-reset
2018-10-09-raspbian-stretch-lite
daan@DESKTOP-OGEP42C:/mnt/d/hackingToolkit/raspberry-pi-factory-reset$ sudo bash ./create-factory-reset 2020-02-13-raspbian-buster-lite
2020-02-13-raspbian-buster-lite
daan@DESKTOP-OGEP42C:/mnt/d/hackingToolkit/raspberry-pi-factory-reset$ nano
.git/                                README.md                            display_funcs
.gitignore                           assets/                              init_resize2.sh
2020-02-13-raspbian-buster-lite.img  create-factory-reset                 raspbian_lite_latest
```
I changed the CURRENT_BASE= to `2020-02-13-raspbian-buster-lite` but that doesnt work

**Comment by tolland** [comment]
I've updated the code to work with 2021-01-11-raspios-buster-armhf-lite and 2021-03-04-raspios-buster-armhf-lite, also I've added the built version of the images to releases section here:
https://github.com/limepepper/raspberry-pi-factory-reset/releases
